//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingflix.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kingflix.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;border-bottom: 1px solid #e6e6e6;&quot;&gt;
        ///    &lt;div style=&quot;padding: 30px 35px;&quot;&gt;
        ///        &lt;p style=&quot;font-weight: bold; color: #ed343d; margin-bottom: 0&quot;&gt;THÔNG TIN TÀI KHOẢN&lt;/p&gt;
        ///        &lt;table&gt;
        ///            &lt;thead&gt;
        ///                &lt;tr&gt;
        ///                    &lt;th&gt;Gói&lt;/th&gt;
        ///                    &lt;th&gt;Tên đăng nhập&lt;/th&gt;
        ///                    &lt;th&gt;Mật khẩu&lt;/th&gt;
        ///                    &lt;th&gt;Profile&lt;/th&gt;
        ///                    &lt;th&gt;Mã PIN&lt;/th&gt;
        ///                    &lt;th&gt;Ngày hết hạn&lt;/th&gt;
        ///                &lt;/tr&gt;
        ///            &lt;/thead&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccountList {
            get {
                return ResourceManager.GetString("AccountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        @media screen and (max-width: 768px) {
        ///            #body {
        ///                width: 100%;
        ///            }
        ///            .display {
        ///                display: block;
        ///            }
        ///            .flex-mid {
        ///                width: 100%;
        ///            }
        ///        }
        ///        @media screen and (min-width: 768px) {
        ///            #body {
        ///                width: 80%;
        ///            }
        ///            .display {
        ///                display: flex;
        ///            }
        ///            .flex-mid {
        ///                width: 50%;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChangeProfile {
            get {
                return ResourceManager.GetString("ChangeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        @media screen and (max-width: 768px) {
        ///            #body {
        ///                width: 100%;
        ///            }
        ///
        ///            .display {
        ///                display: block;
        ///            }
        ///
        ///            .flex-mid {
        ///                width: 100%;
        ///            }
        ///        }
        ///
        ///        @media screen and (min-width: 768px) {
        ///            #body {
        ///                width: 80%;
        ///            }
        ///
        ///            .display {
        ///                display: flex;
        ///            }
        ///
        ///            .flex-mid  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpriedProfile {
            get {
                return ResourceManager.GetString("ExpriedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        #body {
        ///            font: small/ 1.5 Arial,Helvetica,sans-serif;
        ///        }
        ///        @media screen and (max-width: 768px) {
        ///            #body {
        ///                width: 100%;
        ///            }
        ///
        ///            .display {
        ///                display: block;
        ///            }
        ///
        ///            .flex-mid {
        ///                width: 100%;
        ///            }
        ///        }
        ///
        ///        @media screen and (min-width: 768px) {
        ///            #body {
        ///                width: 80%;
        ///            }
        ///
        ///            .display {
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        @media screen and (max-width: 768px) {
        ///            #body {
        ///                width: 100%;
        ///            }
        ///            .display {
        ///                display: block;
        ///            }
        ///            .flex-mid {
        ///                width: 100%;
        ///            }
        ///        }
        ///        @media screen and (min-width: 768px) {
        ///            #body {
        ///                width: 80%;
        ///            }
        ///            .display {
        ///                display: flex;
        ///            }
        ///            .flex-mid {
        ///                width: 50%;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;border-bottom: 1px solid #e6e6e6;&quot;&gt;
        ///    &lt;div style=&quot;padding: 30px 35px;&quot;&gt;
        ///        &lt;p style=&quot;font-weight: bold; color: #ed343d; margin-bottom: 0&quot;&gt;THÔNG TIN TÀI KHOẢN&lt;/p&gt;
        ///        &lt;table&gt;
        ///            &lt;thead&gt;
        ///                &lt;tr&gt;
        ///                    &lt;th&gt;Loại gói&lt;/th&gt;
        ///                    &lt;th&gt;Số tháng&lt;/th&gt;
        ///                    &lt;th&gt;Bảo hành&lt;/th&gt;
        ///                    &lt;th&gt;Loại tài khoản&lt;/th&gt;
        ///                &lt;/tr&gt;
        ///            &lt;/thead&gt;
        ///            &lt;tbody&gt;
        ///                {OrderDetails}
        ///            &lt;/tbody&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
    }
}
