// <auto-generated />
namespace Kingflix.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SettingRefund2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SettingRefund2));
        
        string IMigrationMetadata.Id
        {
            get { return "202103061343331_SettingRefund2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
