// <auto-generated />
namespace Kingflix.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SetUpDbNew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetUpDbNew));
        
        string IMigrationMetadata.Id
        {
            get { return "202101251516482_SetUpDbNew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
